"""alter chats table to be more explicit

Revision ID: 4e3500607a68
Revises: 88a9c098a405
Create Date: 2021-07-08 15:46:11.873087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e3500607a68'
down_revision = '88a9c098a405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'user_id')
    # ### end Alembic commands ###
