"""add about column to group model

Revision ID: 88a9c098a405
Revises: 89011df701d3
Create Date: 2021-07-06 17:32:47.022170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a9c098a405'
down_revision = '89011df701d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'about')
    # ### end Alembic commands ###
