"""add picture column to groups

Revision ID: 89011df701d3
Revises: 1719380416cf
Create Date: 2021-07-02 01:07:15.794445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89011df701d3'
down_revision = '1719380416cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('group_photo', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'group_photo')
    # ### end Alembic commands ###
